version: "3.8"

services:
  db:
    container_name: testdb
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./data/dbdata:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
volumes:
  dbdata:
    driver: local